### ISSUE TITLE
Facebook login is no longer supported by this version of Spotify

### ISSUE THREAD

**Issue by mathisve** [CReimer/aur_spotify#1]
When I try to log in with Facebook after installing, it redirects me to a page with this message:
```
Facebook login is no longer supported by this version of Spotify.
Download the latest version to log in.
```
I'm aware this is not really in your control, but is there any way to circumvent this?
Thanks.

**Comment by CReimer** [comment]
Have you tried using Spotify directly from the snapstore? Does the login with Facebook Work there?

**Comment by mathisve** [comment]
I tried and it does.

**Comment by CReimer** [comment]
Any error on the console? I would try this myself but I don't have Facebook and I definitely won't subscribe to Facebook

**Comment by CReimer** [comment]
Tried it with an account from a friend. Works for me
